version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    networks:
      - guac-network
    restart: unless-stopped

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    networks:
      - guac-network
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacpass123
    ports:
      - "8443:8080"
    depends_on:
      - mysql
      - guacd
    networks:
      - guac-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: imaged-backend
    environment:
      GUAC_BASE: http://guacamole:8080
      GUAC_PUBLIC_BASE: http://20.24.65.164:8443
      GUAC_USER: guacadmin
      GUAC_PASS: guacadmin
      GUAC_DEFAULT_CONN: Imaged
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - guacamole
    networks:
      - guac-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: imaged-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - guac-network
    restart: unless-stopped

networks:
  guac-network:
    driver: bridge

volumes:
  mysql_data: